[features]
seeds = false
skip-lint = false
[programs.devnet]
claiming = "3u19aUs9uQbe6mawUiifjetvtQkxLYzjF5ak1T6sCQXF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ubuntu/fury/deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
